server.port=8080
spring.application.name=blog
spring.web.resources.static-locations=classpath:/static/
spring.thymeleaf.encoding=utf-8
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.jdbc.template.fetch-size=-1
spring.jdbc.template.max-rows=500

#spring.datasource.url=jdbc:oracle:thin:@//192.168.1.20:1521/ORCLPDB
#spring.datasource.url=jdbc:oracle:thin:@//192.168.1.11:1521/ORCLPDB1
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
#spring.datasource.username=blog
#spring.datasource.password=tiger
spring.datasource.username=blog
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.web.resources.chain.enabled=true
spring.web.resources.add-mappings=true
#logging.level.org.springframework.web=DEBUG
logging.level.root=info

